name: SRMA2019_analyses
channels:
  - conda-forge
  - defaults
dependencies:
  - r-base=4.3
  - r-tidyverse
  - r-desc
  - r-table1
  - r-ggplot2
  - r-dplyr
  - r-tidyr
  - r-formattable
  - r-rcurl
  - r-corrplot
  - r-hrbrthemes
  - r-rcolorbrewer
  - r-janitor
  - r-scales
  - r-lemon
  - r-plyr
  - r-hmisc
  - r-mfx
  - r-jtools
  - r-nnet
  - r-margins
  - r-broom.mixed
  - r-ggstance
  - r-stargazer
  - r-data.table
  - r-lubridate
  - r-knitr
  - r-rmarkdown
